server:
  error:
    whitelabel:
      enabled: false
    include-message: always
    port: 8080
spring:
  application:
    name: Architecturizer
  datasource:
    url: jdbc:h2:mem:maindb
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  sql:
    init:
      mode: never
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
